# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 384eda883b3ef993fe32b80ea43990c92ce1ad057cb1c6cdbfb38868fd994a0ea241b31cb9e0bbccea066b063907cc6863e33f505c8ca218cffe9ee29584b773

test:
  secret_key_base: 1360458ff5cee1b534a3ee52bf3860095d7ea235ed190cc550f751a7e92dcfdfa9a34e8e496849afc120b15164f897aeddd3c08297ebd2ea35f6f34138d86060

staging:
  secret_key_base: 9201b0ab5763c63efd15150d528a6be3d08773e9b824197faee485fbed37443874fe0ae033687008da0221f5d8312c4aec65fda8dc6f247707332e17597e149e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
